# Dockerfile.web
FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Add a delay before starting the FastAPI application
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

# Start the FastAPI application
CMD ["/entrypoint.sh"]
